// "use client";

import { useState } from "react";
import Footer from "../{componets}/footer";
import Navbar from "../{componets}/navbar";

interface UsersLayoutProps {
  children: React.ReactNode;
  isLoginPage: boolean; // Add a prop to indicate if it's the login page or not
}

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function UsersLayout({ children }: UsersLayoutProps) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      {/* Pass setSearchQuery function as prop */}
      <main className="flex-grow">{children}</main>
      <Footer />
    </div>
  );
}
