// ./src/app/layout.tsx

import Navbar from "./{componets}/navbar";
import Footer from "./{componets}/footer";
import "animate.css";
import { ToastContainer } from "react-toastify";
import { SearchQueryProvider } from "./hooks/useDataContext";

interface RootLayoutProps {
  children: React.ReactNode;
  isLoginPage: boolean; // Add a prop to indicate if it's the login page or not
}

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className=" bg-gray-200">{children}</body>
    </html>
  );
}
